
use seguridad;

drop table bitacoras;
drop table permisosRoles;
drop table permisosUsuarios;
drop table usuariosRoles;
drop table pantallas;
drop table roles;
drop table usuarios;
drop table sistemas;

---Tablas Principales 
create table usuarios (
idUsuario number generated BY DEFAULT ON NULL AS IDENTITY (START WITH 1) primary key,
nombre varchar(100),
correo varchar(100) ,
clave varchar(100),
estado varchar(20));

create table sistemas (
idSistema number generated BY DEFAULT ON NULL AS IDENTITY (START WITH 1) primary key,
nombre varchar(100),
descripcion varchar(255));

create table roles (
idRol number generated BY DEFAULT ON NULL AS IDENTITY (START WITH 1) primary key,
idSistema number,
nombre varchar(100) ,
descripcion varchar(255), 
foreign key (idSistema) references sistemas(idSistema));

create table pantallas (
idPantalla number generated BY DEFAULT ON NULL AS IDENTITY (START WITH 1) ,
idSistema number,
nombre varchar(100),
descripcion varchar(255),
ruta varchar(255),
foreign key (idSistema) references sistemas(idSistema),
primary key(idPantalla,idSistema));

create table bitacoras (
idBitacora number  generated BY DEFAULT ON NULL AS IDENTITY (START WITH 1) primary key,
idUsuario number,
idSistema number,
idPantalla number,
fecha date,
accion varchar(100),
detalle varchar(255));


---Tablas Intermedias

create table usuariosRoles (
idUsuario number,
idRol number,
primary key (idUsuario, idRol),
foreign key (idUsuario) references usuarios(idUsuario),
foreign key (idRol) references roles(idRol));

create table permisosUsuarios (
idUsuario number,
idSistema number,
idPantalla number,
permisoInsertar number(1),
permisoModificar number(1),
permisoBorrar number(1),
permisoConsultar number(1),
primary key (idUsuario, idPantalla),
foreign key (idUsuario) references usuarios(idUsuario),
foreign key (idPantalla, idSistema) references pantallas(idPantalla, idSistema));


create table permisosRoles (
idRol number,
idSistema number,
idPantalla number,
permisoInsertar number(1),
permisoModificar number(1),
permisoBorrar number(1),
permisoConsultar number(1),
foreign key (idRol) references roles(idRol),
foreign key (idPantalla, idSistema) references pantallas(idPantalla, idSistema),
primary key (idRol, idPantalla));


--------------------------------CAMPO DE PRUEBA-----------------------------

select * from usuarios;
select * from sistemas;
select * from roles;
select * from pantallas;
select * from bitacoras;
select * from usuariosRoles;
select * from permisosUsuarios;
select * from permisosRoles;

drop table bitacoras ;
drop table pantallas ;
drop table permisosRoles;
drop table permisosUsuarios;
drop table roles;
drop table sistemas;
drop table usuarios;
drop table usuariosRoles;

--*******************************************************************************************************************
--*******************************************************************************************************************
--*******************************************************************************************************************
----------------------------------------------------Procedimientos----------------------------------------------------------

--1: Una vez que un usuario cambie de activo a inactivo se borran todos sus permisos y roles
create or replace procedure p_cambioEstado(p_idUsuario NUMBER) 
is
  v_tienePermiso number;
  v_tieneRoles number;

begin
  -- Eliminar permisos directos
  v_tienePermiso:= f_tienePermisos(p_idUsuario);
  if v_tienePermiso = 1 then
      delete from permisosUsuarios
      where idUsuario = p_idUsuario;
   end if;

  -- Eliminar roles
  v_tieneRoles:=f_tieneRoles(p_idUsuario);
  if v_tieneRoles = 1 then
      delete from usuariosRoles
      where idUsuario = p_idUsuario;
    end if;
  
end;
-- 2: Se encarga de por medio del id usuario devolver la vista con los permisos y pantallas que tiene acceso*********************************
--out sys_refcursor es una tabla dinamica en memoria que el procedimiento va a llenar
create or replace procedure p_permisosUsuario ( p_idusuario number, p_resultado out sys_refcursor)
is
begin
    open p_resultado for
        select *
        from v_permisos_usuario
        where idusuario = p_idusuario;
end;

-- 3: Se encarga de eliminar los permisos de un rol en todas las pantallas de un sistema
create or replace procedure P_EliminarPermisosPorRol(
    v_idrol in number,
    v_idsistema in number) is
begin
    delete from permisosroles
    where idrol = p_idrol
    and idpantalla in (
        select idpantalla
        from pantallas
        where idsistema = v_idsistema
    );
    delete from UsuariosRoles
    where idrol = v_idrol
    ;
end;

-- 4:procedimiento para eliminar permisos relacionados a una pantalla
create or replace procedure P_EliminarPermisosPorPantalla(
    v_idPantalla in number,
    v_idSistema in number
) is
begin
    delete from permisosRoles
    where idPantalla = v_idPantalla
    and idSistema = v_idSistema;

    delete from permisosUsuarios
    where idPantalla = v_idPantalla
    and idSistema = v_idSistema;
end;

-- 5: otorgar permisos al rol administrador en todas las pantallas del sistema de seguridad
-- si no existen los permisos, los crea, si ya existen los actualiza
create or replace procedure p_OtorgarPermisosRol(
    v_idRol in number,
    v_idSistema in number
) is
    cursor c_permisos is
        select idpantalla
        from pantallas
        where idSistema = v_idSistema;
    v_cantidad number := 0;
begin
    for i in c_permisos loop
        select count(*) into v_cantidad 
        from permisosRoles
        where idRol = v_idRol and idSistema = v_idSistema and idPantalla = i.idPantalla;

        if v_cantidad = 0 then
            insert into permisosRoles (idRol, idPantalla, idSistema, permisoInsertar, permisoModificar, permisoBorrar, permisoConsultar)
            values (v_idRol, i.idPantalla, v_idSistema, 1, 1, 1, 1);
        else
            update permisosRoles
            set permisoInsertar = 1,
                permisoModificar = 1,
                permisoBorrar = 1,
                permisoConsultar = 1
            where idRol = v_idRol and idSistema = v_idSistema and idPantalla = i.idPantalla; 
        end if;
    end loop;
end;


-- 6: inicia el procedimiento para crear o actualizar  el rol de administrador y otorgar permisos en las pantallas del sistema de seguridad uno
create or replace procedure p_CreacionRoleAdministrador(idSistema IN NUMBER,idAdmin in number)
IS
    v_idSistema NUMBER := idSistema;
    v_idRol NUMBER := 0;
    v_countroleAdmin number :=0;
BEGIN
    v_idRol := F_ObtenerIdRolAdministrador(v_idsistema);
    p_OtorgarPermisosRol(v_idRol, v_idSistema);
    select count(*)into v_countroleAdmin from UsuariosRoles where idrol=v_idrol and idusuario=idAdmin;
    if v_countroleAdmin = 0 then
        insert into  UsuariosRoles values (idAdmin,v_idrol); 
    end if;
END;

--7: procedure que da los permisos en las pantallas del sistema de seguridad  
create or replace procedure p_DarPermisosPantallaSeguridad (v_idAdmin IN NUMBER, v_idSistema IN NUMBER) IS
    cursor c_permisos is
        select idpantalla
        from pantallas
        where idSistema = v_idSistema;
        v_cantidad NUMBER:=0;
BEGIN
    for i in c_permisos loop
        select count(*) into v_cantidad from permisosUsuarios pu join usuarios u on pu.idUsuario = u.idUsuario 
        where u.correo = 'AdminSeguridad@Gmail.com' 
        and pu.idSistema = v_idSistema and pu.idPantalla = i.idPantalla
        and pu.idpantalla = i.idPantalla;
    IF v_cantidad = 0 THEN
        INSERT INTO permisosUsuarios (idUsuario, idPantalla, idSistema, permisoInsertar, permisoModificar, permisoBorrar, permisoConsultar)
        VALUES (v_idAdmin, i.idPantalla, v_idSistema, 1, 1, 1, 1);
    ELSE
        update permisosUsuarios
        set permisoInsertar = 1,
            permisoModificar = 1,
            permisoBorrar = 1,
            permisoConsultar = 1
        where idUsuario = v_idAdmin and idSistema = v_idSistema and idPantalla = i.idPantalla; 
    END IF;
        
    end loop;
END;


-- 8: procedure que verifica si la tabla de usuarios no posee ningún dato (cuando esten todos los usuarios inavilitados)
-- se crea o actualiza un administrador por defecto. Es para que la tabla nunca quede sin administrador,

create or replace procedure p_CrearAdminDefault is
    v_cantidadusuariosactivos number := 0;
    v_existenciaadmin number := 0;
    v_idadmin number := 0; 
begin
    select count(*) into v_cantidadusuariosactivos from usuarios
    where estado = 'Activo';

    if v_cantidadusuariosactivos < 1 then
        if f_ExisteAdminDefault() = 1 then
            update usuarios
            set nombre = 'Administrador',
                clave = 'admin123',
                estado = 'Activo'
            where correo = 'AdminSeguridad@Gmail.com';
        elsif f_ExisteAdminDefault() = 0 then
            insert into usuarios (nombre, correo, clave, estado)
            values ('Administrador', 'AdminSeguridad@Gmail.com', 'admin123', 'Activo');
        end if;

        select idUsuario into v_idadmin from usuarios
        where correo = 'AdminSeguridad@Gmail.com';

        p_DarPermisosPantallaSeguridad(v_idadmin, 8080);
        p_CreacionRoleAdministrador(8080, v_idadmin);
    end if;
end;

--9: procedimiento que crea el rol administrador si no existe algun rol y
--le otorga permisos en todas las pantallas del sistema de seguridad
create or replace procedure p_CreacionRoleAdministradorSinAsignar(idSistema in number)
IS
    v_idSistema number := idSistema;
    v_idRol number := 0;
begin
    v_idRol := F_ObtenerIdRolAdministrador(v_idSistema);
    p_OtorgarPermisosRol(v_idRol, v_idSistema);
end;

-------------------------------------------------------Funciones---------------------------------------------------------------------------------

--1: Verifica si un usuario tiene permisos
create or replace function f_tienePermisos(p_idUsuario number)
return number
is
  v_total number;
begin
  select count(*) into v_total
  from permisosusuarios
  where idusuario = p_idUsuario;

  if v_total > 0 then
    return 1;
  else
    return 0;
  end if;
end;

--2: Verifica si un usuario tiene roles
create or replace function f_tieneRoles(p_idUsuario number)
return number
is
  v_total number;
begin
  select count(*) into v_total
  from usuariosRoles
  where idusuario = p_idUsuario;

  if v_total > 0 then
    return 1;
  else
    return 0;
  end if;
end;

--3: funcion para obtener el id del rol administrador, si no existe lo crea
-- si existe lo retorna
create or replace function f_obteneridroladministrador(p_idSistema in number)
return number is
    v_idrol number;
    v_cantidadroles number;
begin
    -- Crear el rol de administrador si no existe
    select count(*) into v_cantidadroles from roles
    where nombre = 'Administrador' and idSistema = p_idSistema;

    if v_cantidadroles = 0 then
        insert into roles (nombre, descripcion, idSistema)
        values ('Administrador', 'Rol de Administrador ', p_idSistema);
        
        select idRol into v_idrol from roles
        where nombre = 'Administrador' and idSistema = p_idSistema;
        
        return v_idrol;
    else
        select idRol into v_idrol from roles
        where nombre = 'Administrador' and idSistema = p_idSistema;
        
        return v_idrol;
    end if;
end;

--4: verifica que exista el administrador por defecto, si no existe devuelve 0, si existe devuelve 1
create or replace function f_ExisteAdminDefault
return number is
    v_count number := 0;
    v_activo number := 0;
begin
    select count(*) into v_count
    from usuarios
    where correo = 'AdminSeguridad@Gmail.com';

    if v_count > 0 then
        select count(*) into v_activo from usuarios where estado = 'Activo';
        if v_activo > 0 then
            return 2;
        else
            return 1;
        end if;
    else
        return 0;
    end if;
end;

---------------------------------------------------------Triggers---------------------------------------------------------------------------------

--1: Cuando se edite se comprueba si el nuevo valor es inactivo, si es asi se llama al procedimiento para eliminar sus roles y permisos
create or replace trigger t_usuarioInactivo
after update on usuarios
for each row
begin
  if :old.estado = 'Activo' and :new.estado = 'Inactivo' then
    p_cambioEstado(:new.idusuario);
  end if;
end;

-- 2: trigger que se ejecuta despues de actualizar un usuario, y verifica si el admin existe,
create trigger t_VerificacionUsuarioAdmin
after update on usuarios
begin
    p_CrearAdminDefault;
end;

--3: Es un trigger que se ejecuta antes de eliminar un rol, y elimina los permisos asociados a ese rol en todas las pantallas de un sistema,
-- aparte de su asignacion de usuarios.
create or replace trigger t_eliminarpermisosrol
after delete on roles
for each row
begin
    p_eliminarpermisosporrol(:old.idrol, :old.idsistema);
end;

--4: Es un trigger que se ejecuta antes de eliminar una pantalla, y elimina los permisos asociados a esa pantalla en todos los roles,

create or replace trigger t_EliminarPermisosPantalla
before delete on pantallas
for each row
begin
    p_EliminarPermisosPorPantalla(:old.idPantalla, :old.idSistema);
end;

-- 5:trigger para crear un rol administrador si no existe el rol de administrador en cada sistema
create or replace trigger t_crearroleadministrador
after delete on roles
declare
    v_idsistema number;
    v_cantidadroles number;
begin
    -- por cada sistema existente en la tabla sistemas
    for i in (select idsistema from sistemas) loop
        
        -- contar roles para ese sistema
        select count(*) into v_cantidadroles
        from roles
        where idsistema = i.idsistema;
        
        -- si para ese sistema no quedó ningún rol
        if v_cantidadroles = 0 then
            -- crear el rol administrador para ese sistema
            p_creacionroleadministradorsinasignar(i.idsistema);
        end if;
    end loop;
end;


----------------------------------------------------Indices-------------------------------------------------------------------------

-- 1: Para consultas como "todos los usuarios con un rol especifico", esto las acelera�.
create index idx_usuariosRoles_idRol on usuariosRoles(idRol);
create index idx_usuariosRoles_idUsuario on usuariosRoles(idUsuario);

-- 2: Para verificar rapidamente que permisos tiene un usuario sobre una pantalla especifica.
create index idx_permisoUsuario_idUsuario on permisosUsuarios(idUsuario);
create index idx_permisoUsuario_idPantalla on permisosUsuarios(idPantalla);

-- 3: Para verificar permisos de un rol especifico de forma eficiente.
create index idx_permisoRol_idRol on permisosRoles(idRol);
create index idx_permisoRol_idPantalla on permisosRoles(idPantalla);

-- 4: Para acelerar las busqueda por el nombre del rol
create index idx_roles_nombre on roles(nombre);

----------------------------------------------------Vistas----------------------------------------------------------------------------------------

-- Es solo una idea, pero seria crear una funcion que entre el id de usuario y segun ese id retorne esta vista que son los permisos que posee
-- en un sistema o pantalla dada
create or replace view v_permisos_usuario as

-- Permisos directos
    select u.idusuario,pu.idpantalla,pu.idsistema,p.nombre as nombre_pantalla,pu.permisoInsertar,pu.permisoModificar, 
    pu.permisoBorrar, pu.permisoConsultar from permisosusuarios pu
    join usuarios u on u.idusuario = pu.idusuario
    join pantallas p on p.idpantalla = pu.idpantalla and p.idsistema = pu.idsistema
union
-- Permisos por roles
    select ur.idusuario,pr.idpantalla,pr.idsistema,p.nombre as nombre_pantalla,pr.permisoInsertar,pr.permisoModificar,pr.permisoBorrar,
    pr.permisoConsultar from usuariosroles ur
    join roles r on ur.idrol = r.idrol
    join permisosroles pr on ur.idrol = pr.idrol and r.idSistema = pr.idSistema
    join pantallas p on p.idpantalla = pr.idpantalla and p.idsistema = pr.idsistema;















