use seguridad;


drop table bitacora ;
drop table pantallas ;
drop table permisosRoles;
drop table permisosUsuarios;
drop table roles;
drop table sistemas;
drop table usuarios;
drop table usuariosRoles;

---Tablas Principales 
create table usuarios (
idUsuario number generated BY DEFAULT ON NULL AS IDENTITY (START WITH 1) primary key ,
nombre varchar(255),
correo varchar(255) ,
clave varchar(255),
estado varchar(50));

create table sistemas (
idSistema number generated BY DEFAULT ON NULL AS IDENTITY (START WITH 1) primary key,
nombre varchar(100),
descripcion varchar(255)
);

create table roles (
idRol number generated BY DEFAULT ON NULL AS IDENTITY (START WITH 1) primary key ,
idSistema number,
nombre varchar(100) ,
descripcion varchar(255), 
foreign key (idSistema) references sistemas(idSistema)) ;


create table pantallas (
idPantalla number generated BY DEFAULT ON NULL AS IDENTITY (START WITH 1) ,
idSistema number,
nombre varchar(100),
descripcion varchar(255),
ruta varchar(255),
foreign key (idSistema) references sistemas(idSistema),
primary key(idPantalla,idSistema));

create table bitacoras (
idBitacora number generated BY DEFAULT ON NULL AS IDENTITY (START WITH 1) primary key,
idUsuario number,
idSistema number,
idPantalla number,
fecha date,
accion varchar(255),
detalle varchar(255),
foreign key (idUsuario) references usuarios(idUsuario));

---Tablas Intermedias

create table usuariosRoles (
idUsuario  number,
idRol number,
primary key (idUsuario, idRol),
foreign key (idUsuario) references usuarios(idUsuario),
foreign key (idRol) references roles(idRol));

create table permisosUsuarios (
idUsuario number,
idPantalla number,
idSistema number,
permisoInsertar number(1),
permisoModificar number(1),
permisoBorrar number(1),
permisoConsultar number(1),
primary key (idUsuario, idPantalla, idSistema),
foreign key (idUsuario) references usuarios(idUsuario),
foreign key (idPantalla, idSistema) references pantallas(idPantalla, idSistema));


create table permisosRoles (
idRol number,
idPantalla number,
idSistema number,
permisoInsertar number(1),
permisoModificar number(1),
permisoBorrar number(1),
permisoConsultar number(1),
primary key (idRol, idPantalla,idSistema),
foreign key (idRol) references roles(idRol),
foreign key (idPantalla, idSistema) references pantallas(idPantalla, idSistema));





----------------------------------------------------Procedimientos----------------------------------------------------------

--1: Una vez que un usuario cambie de activo a inactivo se borran todos sus permisos y roles
create or replace procedure p_cambioEstado(p_idUsuario NUMBER) 
is
v_tienePermiso number;
v_tieneRoles number;

begin
-- Eliminar permisos directos
    v_tienePermiso:= f_tienePermisos(p_idUsuario);
    if v_tienePermiso = 1 then
        delete from permisosUsuarios
        where idUsuario = p_idUsuario;
    end if;

-- Eliminar roles
    v_tieneRoles:=f_tieneRoles(p_idUsuario);
    if v_tieneRoles = 1 then
        delete from usuariosRoles
        where idUsuario = p_idUsuario;
    end if;
end;


-- 2: Se encarga de por medio del id usuario devolver la vista con los permisos y pantallas que tiene acceso
--out sys_refcursor es una tabla dinámica en memoria que el procedimiento va a llenar
create or replace procedure p_permisosUsuario ( p_idusuario number, p_resultado out sys_refcursor)
is
begin
    open p_resultado for
        select *
        from v_permisosUsuario
        where idusuario = p_idusuario;
end;

-- 3: Se encarga de eliminar los permisos de un rol en todas las pantallas de un sistema
CREATE OR REPLACE PROCEDURE P_EliminarPermisosPorRol(
    p_idRol IN NUMBER,
    p_idSistema IN NUMBER
) IS
BEGIN
    DELETE FROM permisosRoles
    WHERE idRol = p_idRol
    AND idSistema = p_idSistema;
END;

-- 4:-- procedimiento para eliminar permisos relacionados a una pantalla
CREATE OR REPLACE PROCEDURE P_EliminarPermisosPorPantalla(
    p_idPantalla IN NUMBER,
    p_idSistema IN NUMBER
) IS
BEGIN
    DELETE FROM permisosRoles
    WHERE idPantalla = p_idPantalla
    AND idSistema = p_idSistema;

    DELETE FROM permisosUsuarios
    WHERE idPantalla = p_idPantalla
    AND idSistema = p_idSistema;
END;

-- 5: otorgar permisos al rol administrador en todas las pantallas del sistema de seguridad
-- si no existen los permisos, los crea, si ya existen los actualiza
create or replace procedure p_OtorgarPermisosRol(
    v_idRol IN NUMBER,
    v_idSistema IN NUMBER
) IS
    cursor c_permisos is
        select idpantalla
        from pantallas
        where idSistema = v_idSistema;
    v_cantidad NUMBER := 0;
BEGIN
    for i in c_permisos loop
        select count(*) into v_cantidad 
        from permisosRoles
        where idRol = v_idRol and idSistema = v_idSistema and idPantalla = i.idPantalla;
        IF v_cantidad = 0 THEN
            INSERT INTO permisosRoles (idRol, idPantalla, idSistema, permisoInsertar, permisoModificar, permisoBorrar, permisoConsultar)
            VALUES (v_idRol, i.idPantalla, v_idSistema, 1, 1, 1, 1);
        ELSE
            update permisosRoles
            set permisoInsertar = 1,
                permisoModificar = 1,
                permisoBorrar = 1,
                permisoConsultar = 1
            where idRol = v_idRol and idSistema = v_idSistema and idPantalla = i.idPantalla; 
        END IF;
    end loop;
END;

-- 6: inicia el procedimiento para crear o actualizar  el rol de administrador y otorgar permisos en las pantallas del sistema de seguridad uno
create or replace procedure p_CreacionRoleAdministrador(idSistema IN NUMBER,idAdmin in number)
IS
    v_idSistema NUMBER := idSistema;
    v_idRol NUMBER := 0;
    v_countroleAdmin number :=0;
BEGIN
    v_idRol := F_ObtenerIdRolAdministrador();
    p_OtorgarPermisosRol(v_idRol, v_idSistema);
    select count(*)into v_countroleAdmin from UsuariosRoles where idrol=v_idrol and idusuario=idAdmin;
    if v_countroleAdmin = 0 then
        insert into  UsuariosRoles values (idAdmin,v_idrol); 
    end if;
END;

--7: procedure que da los permisos en las pantallas del sistema de seguridad  
create or replace procedure p_DarPermisosPantallaSeguridad (v_idAdmin IN NUMBER, v_idSistema IN NUMBER) IS
    cursor c_permisos is
        select idpantalla
        from pantallas
        where idSistema = v_idSistema;
        v_cantidad NUMBER:=0;
BEGIN
    for i in c_permisos loop
        select count(*) into v_cantidad from permisosUsuarios pu join usuarios u on pu.idUsuario = u.idUsuario 
        where u.correo = 'AdminSeguridad@Gmail.com' 
        and pu.idSistema = v_idSistema and pu.idPantalla = i.idPantalla
        and pu.idpantalla = i.idPantalla;
    IF v_cantidad = 0 THEN
        INSERT INTO permisosUsuarios (idUsuario, idPantalla, idSistema, permisoInsertar, permisoModificar, permisoBorrar, permisoConsultar)
        VALUES (v_idAdmin, i.idPantalla, v_idSistema, 1, 1, 1, 1);
    ELSE
        update permisosUsuarios
        set permisoInsertar = 1,
            permisoModificar = 1,
            permisoBorrar = 1,
            permisoConsultar = 1
        where idUsuario = v_idAdmin and idSistema = v_idSistema and idPantalla = i.idPantalla; 
    END IF;
        
    end loop;
END;
-- 8: procedure que verifica si la tabla de usuarios no posee ningún dato (cuando esten todos los usuarios inavilitados)
-- se crea o actualiza un administrador por defecto. Es para que la tabla nunca quede sin administrador,

CREATE OR REPLACE PROCEDURE p_CrearAdminDefault IS
    v_cantidadUsuariosActivos NUMBER := 0;
    v_existenciaAdmin NUMBER := 0;
    v_idAdmin NUMBER := 0; 
BEGIN
    SELECT COUNT(*) INTO v_cantidadUsuariosActivos FROM usuarios
        WHERE estado = 'Activo';
    IF v_cantidadUsuariosActivos < 1 THEN
        IF f_ExisteAdminDefault() = 1 THEN
            UPDATE usuarios
            SET nombre = 'Administrador',
                clave = 'admin123',
                estado = 'Activo'
            WHERE correo = 'AdminSeguridad@Gmail.com';
        ELSif f_ExisteAdminDefault() = 0 THEN
            INSERT INTO usuarios ( nombre, correo, clave, estado)
            VALUES ( 'Administrador', 'AdminSeguridad@Gmail.com', 'admin123', 'Activo');
        END IF;
        SELECT idUsuario INTO v_idAdmin FROM usuarios
        WHERE correo = 'AdminSeguridad@Gmail.com';
        p_DarPermisosPantallaSeguridad(v_idAdmin, 8080);
        p_CreacionRoleAdministrador(8080,v_idAdmin);
        
    END IF;
    
END;
--9: procedimiento que crea el rol administrador si no existe algun rol, y le otorga permisos en todas las pantallas del sistema de seguridad
create or replace procedure p_CreacionRoleAdministradorSinAsignar(idSistema IN NUMBER)
IS
    v_idSistema NUMBER := idSistema;
    v_idRol NUMBER := 0;
BEGIN
    v_idRol := F_ObtenerIdRolAdministrador();
    p_OtorgarPermisosRol(v_idRol, v_idSistema);
END;

-------------------------------------------------------Funciones---------------------------------------------------------------------------------

--1: Verifica si un usuario tiene permisos
create or replace function f_tienePermisos(p_idUsuario number)
return number
is
  v_total number;
begin
  select count(*) into v_total
  from permisosusuarios
  where idusuario = p_idUsuario;

  if v_total > 0 then
    return 1;
  else
    return 0;
  end if;
end;

--2: Verifica si un usuario tiene roles
create or replace function f_tieneRoles(p_idUsuario number)
return number
is
  v_total number;
begin
  select count(*) into v_total
  from usuariosRoles
  where idusuario = p_idUsuario;

  if v_total > 0 then
    return 1;
  else
    return 0;
  end if;
end;

--3: funcion para obtener el id del rol administrador, si no existe lo crea
-- si existe lo retorna
create or replace FUNCTION F_ObtenerIdRolAdministrador
RETURN NUMBER IS
    v_idRol NUMBER;
    v_CantidadRoles NUMBER;
BEGIN
    -- Crear el rol de administrador si no existe
    select count(*) into v_CantidadRoles FROM roles
    WHERE nombre = 'Administrador' AND idSistema = 8080;

    IF v_CantidadRoles = 0 THEN
        INSERT INTO roles (nombre, descripcion, idSistema)
        VALUES ('Administrador', 'Rol de Administrador para seguridad', 8080);
        select idRol into v_idRol FROM roles
        WHERE nombre = 'Administrador' AND idSistema = 8080;
        RETURN v_idRol;
    ELSE
        SELECT idRol INTO v_idRol FROM roles
        WHERE nombre = 'Administrador' AND idSistema = 8080;
        RETURN v_idRol;
    END IF;
END;

--4: verifica que exista el administrador por defecto, si no existe devuelve 0, si existe devuelve 1
CREATE OR REPLACE FUNCTION f_ExisteAdminDefault 
RETURN NUMBER IS
    v_Count NUMBER := 0;
    v_Activo number := 0;
BEGIN
    SELECT COUNT(*) INTO v_Count 
    FROM usuarios 
    WHERE 
        correo = 'AdminSeguridad@Gmail.com';
    IF v_Count > 0 THEN
        SELECT count(*) INTO v_Activo FROM usuarios WHERE estado = 'Activo';
        IF v_Activo > 0 THEN
            RETURN 2;
        ELSE
            RETURN 1;
        END IF;
    ELSE
        RETURN 0;
    END IF;
END;
---------------------------------------------------------Triggers---------------------------------------------------------------------------------

--1: Cuando se edite se comprueba si el nuevo valor es inactivo, si es asi se llama al procedimiento para eliminar sus roles y permisos
create or replace trigger t_usuarioInactivo
after update on usuarios
for each row
begin
  if :old.estado = 'Activo' and :new.estado = 'Inactivo' then
    p_cambioEstado(:new.idusuario);
  end if;
end;
-- 2: trigger que se ejecuta después de actualizar un usuario, y verifica si el admin existe,
CREATE TRIGGER t_VerificaciónUsuarioAdmin 
AFTER UPDATE ON usuarios
BEGIN
    p_CrearAdminDefault;
END; 
--3: Es un trigger que se ejecuta antes de eliminar un rol, y elimina los permisos asociados a ese rol en todas las pantallas de un sistema,
-- aparte de su asignación de usuarios.
CREATE TRIGGER t_EliminarPermisosRol
BEFORE DELETE ON roles
FOR EACH ROW
BEGIN
    p_EliminarPermisosPorRol(:OLD.idRol, :OLD.idSistema);
END;

--4: Es un trigger que se ejecuta antes de eliminar una pantalla, y elimina los permisos asociados a esa pantalla en todos los roles,

CREATE or replace TRIGGER t_EliminarPermisosPantalla
BEFORE DELETE ON pantallas
FOR EACH ROW
BEGIN
    P_EliminarPermisosPorPantalla(:OLD.idPantalla, :OLD.idSistema);
END;

-- 5:trigger para crear un rol administrador si no existe algun rol, se ejecuta despues de eliminar 
-- todos los datos de la sentencia por eso no se especifica el for each row
-- en el trigger, se ejecuta una vez al eliminar todos los roles
create or replace trigger t_crearRoleAdministrador
AFTER delete ON roles
DECLARE
    v_cantidadRoles NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cantidadRoles FROM roles ;
    IF v_cantidadRoles = 0 THEN
        p_CreacionRoleAdministradorSinAsignar(8080);
    END IF;
END;


----------------------------------------------------Indices-------------------------------------------------------------------------

-- 1: Para consultas como "todos los usuarios con un rol específico", esto las acelerará.
create index idx_usuariosRoles_idRol on usuariosRoles(idRol);
create index idx_usuariosRoles_idUsuario on usuariosRoles(idUsuario);

-- 2: Para verificar rápidamente qué permisos tiene un usuario sobre una pantalla específica.
create index idx_permisoUsuario_idUsuario on permisosUsuarios(idUsuario);
create index idx_permisoUsuario_idPantalla on permisosUsuarios(idPantalla);

-- 3: Para verificar permisos de un rol específico de forma eficiente.
create index idx_permisoRol_idRol on permisosRoles(idRol);
create index idx_permisoRol_idPantalla on permisosRoles(idPantalla);

-- 4: Para acelerar las búsquedad por el nombre del rol
create index idx_roles_nombre on roles(nombre);




----------------------------------------------------Vistas----------------------------------------------------------------------------------------

-- Es solo una idea, pero seria crear una funcion que entre el id de usuario y segun ese id retorne esta vista que son los permisos que posee
-- en un sistema o pantalla dada
create or replace view v_permisosUsuario as
    
    -- Permisos directos
    select u.idusuario,pu.idpantalla,pu.idsistema, p.nombre as nombre_pantalla, pu.permisoInsertar,pu.permisoModificar, 
    pu.permisoBorrar, pu.permisoConsultar from permisosusuarios pu
    join usuarios u on u.idusuario = pu.idusuario
    join pantallas p on p.idpantalla = pu.idpantalla and p.idsistema = pu.idsistema
union
    
    -- Permisos por roles
    select ur.idusuario, pr.idpantalla, pr.idsistema, p.nombre as nombre_pantalla, pr.permisoInsertar, pr.permisoModificar, pr.permisoBorrar,
    pr.permisoConsultar from usuariosroles ur
    join permisosroles pr on ur.idrol = pr.idrol and ur.idsistema = pr.idsistema
    join pantallas p on p.idpantalla = pr.idpantalla and p.idsistema = pr.idsistema;



------------------------------------------------------Verificaciones--------------------------------------------------------------------------------

-- Agregar usuario
insert into usuarios (idusuario, nombre, correo, clave, estado)
values (1001, 'usuario prueba', 'prueba@correo.com', '1234', 'Activo');

-- Agregar pantalla
insert into pantallas (idpantalla, idsistema, nombre, descripcion, ruta)
values (1, 1, 'Pantalla Principal', 'Descripción', '/ruta');

-- Agregar sistemas
insert into sistemas (idsistema, nombre, descripcion)
values (1, 'Sistema de Prueba', 'Descripción del sistema');

-- Agregar permisos de usuarios
insert into permisosusuarios (idusuario, idpantalla, idsistema, permisoInsertar, permisoModificar, permisoBorrar, permisoConsultar)
values (1001, 1, 1, 1, 1, 1, 1);

-- Agregar rol a usuario
insert into usuariosroles (idusuario, idrol, idsistema)
values (1001, 1, 1);

-- Ver 
select * from usuarios;
select * from usuariosroles;

--Cambiar valor de inactivo para verificar que funcione el trigger, procedimiento, y funciones de activo a inactivo
update usuarios
set estado = 'Inactivo'
where idusuario = 1001;























