CREATE TABLESPACE SEGURIDAD_PROYECTO
DATAFILE 'C:\ORACLE\PRODUCT\21C\ORADATA\XE\SEGURIDAD_PROYECTO01.DBF'  
SIZE 100M                                
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED 
LOGGING;                                 

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER SEGURIDAD_USUARIO
IDENTIFIED BY "ucr2025" 
DEFAULT TABLESPACE SEGURIDAD_PROYECTO   
TEMPORARY TABLESPACE TEMP;      

GRANT CONNECT TO SEGURIDAD_USUARIO;

GRANT RESOURCE TO SEGURIDAD_USUARIO;

ALTER USER SEGURIDAD_USUARIO QUOTA UNLIMITED ON SEGURIDAD_PROYECTO;
